# Generated by Django 5.2.3 on 2025-06-20 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='info',
            old_name='text',
            new_name='data',
        ),
    ]
