# Generated by Django 5.2.3 on 2025-06-21 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_text_info_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('photo', models.ImageField(upload_to='')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='info',
            options={'ordering': ('tag',), 'verbose_name': 'Info', 'verbose_name_plural': 'Info'},
        ),
        migrations.AlterModelTableComment(
            name='info',
            table_comment='Configs and information',
        ),
    ]
