# Generated by Django 5.2.3 on 2025-06-21 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_category_alter_info_options_alter_info_table_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('tag',), 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelTableComment(
            name='category',
            table_comment='Configs and information',
        ),
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.SlugField(default='', null=True),
        ),
    ]
