# Generated by Django 5.2.3 on 2025-06-21 20:55

import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_category_options_alter_category_table_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(storage=main.models.UUIDFileStorage, upload_to=''),
        ),
        migrations.AlterField(
            model_name='category',
            name='tag',
            field=models.SlugField(default='', null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='info',
            name='tag',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
