# Generated by Django 5.2.3 on 2025-06-21 22:41

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_category_photo_alter_category_tag_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.SlugField(default='', null=True, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('photo', models.ImageField(storage=main.models.UUIDFileStorage, upload_to='')),
                ('characteristics', models.FileField(storage=main.models.UUIDFileStorage, upload_to='products_data', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.xls', '.xlsx'])])),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
                'db_table_comment': 'Products',
                'ordering': ('tag',),
            },
        ),
        migrations.AlterModelTableComment(
            name='category',
            table_comment='Product`s categories',
        ),
    ]
