# Generated by Django 5.2.3 on 2025-06-23 15:36

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='characteristics',
            field=models.FileField(storage=main.models.UUIDFileStorage, upload_to='products_data', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
    ]
