# Generated by Django 5.2.3 on 2025-06-23 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_product_characteristics'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='addingTime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
