# Generated by Django 5.2.3 on 2025-06-30 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_categorygroup_category_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='categories',
            new_name='categoryGroup',
        ),
    ]
