# Generated by Django 5.2.3 on 2025-06-30 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_rename_categories_category_categorygroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categorygroup',
            name='tag',
            field=models.SlugField(default='', max_length=25, unique=True),
        ),
    ]
