# Generated by Django 5.2.3 on 2025-07-20 11:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_categorygroup_tag'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categorygroup',
            options={'ordering': ('tag',), 'verbose_name': 'Category Group', 'verbose_name_plural': 'Cat groups'},
        ),
        migrations.AlterModelTableComment(
            name='categorygroup',
            table_comment='Category (of products) groups',
        ),
        migrations.AlterField(
            model_name='category',
            name='categoryGroup',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.categorygroup'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=96),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=96),
        ),
    ]
