# Generated by Django 5.2.4 on 2025-07-22 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_categorygroup_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='categoryGroup',
        ),
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
        migrations.RemoveField(
            model_name='category',
            name='photo',
        ),
        migrations.AddField(
            model_name='category',
            name='subCategories',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.category'),
        ),
    ]
