# Generated by Django 5.2.4 on 2025-07-22 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_remove_category_categorygroup_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='subCategories',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='main.category'),
        ),
    ]
