# Generated by Django 5.2.4 on 2025-07-22 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_category_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='subCategories',
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcat', to='main.category'),
        ),
    ]
