# Generated by Django 5.2.4 on 2025-07-22 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_category_subcategories_category_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.IntegerField(blank=True, default=10, null=True),
        ),
    ]
