# Generated by Django 5.2.3 on 2025-07-30 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_category_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CategoryGroup',
        ),
    ]
