# Generated by Django 5.2.3 on 2025-07-30 11:30

import django.core.validators
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_delete_categorygroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_uk',
            field=models.CharField(max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_en',
            field=models.FileField(null=True, storage=main.models.UUIDFileStorage, upload_to='products_data', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='characteristics_uk',
            field=models.FileField(null=True, storage=main.models.UUIDFileStorage, upload_to='products_data', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['xls', 'xlsx'])]),
        ),
        migrations.AddField(
            model_name='product',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='description_uk',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_en',
            field=models.CharField(max_length=96, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='name_uk',
            field=models.CharField(max_length=96, null=True),
        ),
    ]
